# Configuración usando solo un archivo yml.

# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: stackoverflow
  name: stackoverflow-frontend-deploy
  labels:
    rol: frontend
spec:
  replicas: 2
  selector:
    #Estas etiquetas identifican a los pods asociados a este deployment
    matchLabels:
      rol: frontend
  template:
    # Este es un PodTemplate
    metadata:
      labels:
        rol: frontend 
    spec:
      containers:
        - name: stackoverflow-frontend-container
          image: stackoverflow-frontend-img
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
---
# Service
apiVersion: v1
kind: Service
metadata:
  namespace: stackoverflow
  name: stackoverflow-frontend-service
spec:
  ports:
    - name: http-frontend
      port: 8061
      targetPort: 80 
  selector:
    rol: frontend
  type: LoadBalancer